### ISSUE TITLE
grace: command not found

### ISSUE THREAD

**Issue by ckaock** [Thunf/aliAR#2]
Hi：
已经安装了grace，但是提示grace: command not found

**Comment by qcha0** [comment]
@ckaock
何种方式安装的grace？编译安装？包管理工具安装？
啥系统？
信息给多一点吧…

**Comment by xiongwilee** [comment]
grace相关的问题可以去参考: [vhost多站点配置](https://github.com/xiongwilee/koa-grace#vhost多站点配置) ，
如果还是有问题，可以在[koa-grace](https://github.com/xiongwilee/koa-grace) 提ISSUE

**Comment by Thunf** [comment]
@ckaock 不好意思，grace的command还未发布开源版本，readme文档已更新。

grace使用方法请参考楼上 @xiongwilee  给出的参考，很简单的~

**Comment by ckaock** [comment]
感谢@Agnewee @xiongwilee 的回复，得知原因是grace的command未发布开源版本。后经参考@Thunf 更新的文档说明，运行成功。
